rm -rf /storage/emulated/0/Android/data/com.miui.gallery/files/gallery_disk_cache > /dev/null 2>&1
rm -rf /data/system/dropborm > /dev/null 2>&1
rm -rf /data/system/usagestats > /dev/null 2>&1
rm -rf /sdcard/bugreports/* > /dev/null 2>&1
rm -rf /sdcard/DCIM/.thumbnails > /dev/null 2>&1
rm -rf /data/log > /dev/null 2>&1
rm -rf /sdcard/Android/data/*/cache > /dev/null 2>&1
rm -rf /data/data/*/cache > /dev/null 2>&1
rm -rf /data/local/tmp/* > /dev/null 2>&1
rm -rf /data/logger > /dev/null 2>&1
rm -rf /sdcard/LOST.DIR > /dev/null 2>&1
rm -rf /data/anr > /dev/null 2>&1
rm -rf /data/tombstones > /dev/null 2>&1
rm -rf /data/adb/lspd/log > /dev/null 2>&1
rm -rf /data/adb/lspd/log.old > /dev/null 2>&1
rm -rf /data/system/*/logging/server_logging/log > /dev/null 2>&1
rm -rf /storage/emulated/0/Fox/logs > /dev/null 2>&1
rm -rf /data/misc/update_engine_log > /dev/null 2>&1
rm -rf /data/system/*/tmp/runtime.log > /dev/null 2>&1
rm -rf /data/log > /dev/null 2>&1
rm -rf /data/logger > /dev/null 2>&1
rm -rf /data/data/com.miui.gallery/files/debug_log > /dev/null 2>&1
rm -rf /data/data/com.xiaomi.account/files/dump/log > /dev/null 2>&1
rm -rf /data/data/*/files/Logs > /dev/null 2>&1
rm -rf /storage/emulated/0/.system_config > /dev/null 2>&1
rm -rf /storage/emulated/0/.SHAREit > /dev/null 2>&1
rm -rf /storage/emulated/0/.android > /dev/null 2>&1
rm -rf /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/.Thumbs > /dev/null 2>&1
rm -rf /storage/emulated/0/Pictures/.thumbnails > /dev/null 2>&1
rm -rf /storage/emulated/0/MIUI/debug_log > /dev/null 2>&1
rm -rf /sdcard/LOST.DIR > /dev/null 2>&1
rm -rf /sdcard/bugreports/* > /dev/null 2>&1
rm -rf /sdcard/DCIM/.thumbnails > /dev/null 2>&1
rm -rf /storage/emulated/0/Movies/.thumbnails > /dev/null 2>&1
rm -rf /storage/emulated/0/ramdump > /dev/null 2>&1
rm -rf /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/.trash > /dev/null 2>&1
rm -rf /storage/emulated/0/Fox/logs > /dev/null 2>&1
rm -rf /storage/emulated/0/Music/.thumbnails > /dev/null 2>&1
rm -rf /storage/emulated/0/MIUI/BugReportCache > /dev/null 2>&1
rm -rf /storage/*/LOST.DIR > /dev/null 2>&1
rm -rf /storage/*/*/LOST.DIR